# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stepan Filatov's Blog
email: filatov.st@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My personal notes and articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sfilatov.github.io" # the base hostname & protocol for your site
twitter_username: sfilatov
github_username:  sfilatov

# Build settings
markdown: kramdown

exclude: ["docker-compose.yml", "Gemfile", "Gemfile.lock", ".gitignore"]
